stages:
  - frontend
  - backend
  - deploy

default:
  tags:
    - local-docker

frontend_build:
  stage: frontend
  script:
    - cd frontend
    - npm.cmd install
    - npm.cmd run build

backend_test:
  stage: backend
  script:
    - cd backend
    - npm.cmd install
    - npm.cmd run test

backend_build:
  stage: backend
  script:
    - cd backend
    - npm.cmd install
    - npm.cmd run build

deploy_local:
  stage: deploy
  needs:
    - frontend_build
    - backend_test
    - backend_build
  script:
    - docker compose down
    - if ($LASTEXITCODE -ne 0) { Write-Host "Nothing to stop"; $global:LASTEXITCODE = 0 }
    - docker compose up -d --build
  only:
    - main
